### ISSUE TITLE
The mean of the result trace word “anon0” or “anon3_Then”

### ISSUE THREAD

**Issue by ZJLavender** [boogie-org/boogie#102]
We make the boogie result:
"
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
/Users/jiezhang/Desktop/Time/HyperFlow-Prover/1537686751792b2b15c44af2e5fa1e376979f0272dc34.bpl(20,5): Error BP5003: A postcondition might not hold on this return path.
/Users/jiezhang/Desktop/Time/HyperFlow-Prover/1537686751792b2b15c44af2e5fa1e376979f0272dc34.bpl(16,1): Related location: This is the postcondition that might not hold.
Execution trace:
    /Users/jiezhang/Desktop/Time/HyperFlow-Prover/1537686751792b2b15c44af2e5fa1e376979f0272dc34.bpl(18,5): anon0
    /Users/jiezhang/Desktop/Time/HyperFlow-Prover/1537686751792b2b15c44af2e5fa1e376979f0272dc34.bpl(19,11): anon3_Then

Boogie program verifier finished with 0 verified, 1 error
"
to
"
{
    "boogieSourceResult": [
        {
            "trace": [
                {
                    "column": 3, 
                    "description": " anon0", 
                    "line": 11
                }, 
                {
                    "column": 11, 
                    "description": " anon4_Then", 
                    "line": 12
                }, 
                {
                    "column": 3, 
                    "description": " anon3", 
                    "line": 16
                }
            ], 
            "wrongPoint": {
                "column": 3, 
                "description": " BP5001: This assertion might not hold.", 
                "line": 16
            }
        }
    ], 
    "errorCount": 1, 
    "verifiedCount": 0
}
"
And where I can found docunemt about the meaning  about "BP5001" in error or "anon0"、"anon3_Then" in trace?Because i need this explain to other people why them code is wrong.
I need help ,thank you

**Comment by bkragl** [comment]
**Error Codes**

BP5xxx are verification error codes.  

BP5001: assertion might not hold
BP5002: precondition for call might not hold
BP5003: postcondition might not hold
BP5004: loop invariant might not hold on entry
BP5005: loop invariant might not be maintained

**Unstructured Code**

Boogie programs are translated into unstructured programs for verification. In the resulting unstructured programs, "anon0", "anon3_Then", etc. are labels generated for basic code blocks. Most likely you won't need that information, because the line/column numbers in the output point to the corresponding location in the original program.

If you want to know how the unstructured program looks like, run Boogie with the options /printUnstructured /print:-.
