### ISSUE TITLE
How to overload operator /  and %

### ISSUE THREAD

**Issue by ZJLavender** [boogie-org/boogie#103]
Dear Boogie developer
I conversion Solidity to Boogie and they Division and modulo operators are different.So I use function to solve this problem,like below:
`function MOD(int,int) returns(int);
function DIV(int,int) returns(int);

//对除法计算结果的定义
axiom(forall x:int, y:int :: {DIV(x,y)}
  x >= 0 ==> DIV(x,y) == x div y
);
axiom(forall x:int, y:int :: {DIV(x,y)}
  x < 0 ==> -DIV(-x,y) == (-x) div y
);

//介绍了取模的计算方式
axiom(forall x:int, y:int :: {MOD(x,y)} 
   x >= 0 ==> MOD(x,y) == x mod y
);
axiom(forall x:int, y:int :: {MOD(x,y)} 
   x < 0 ==> -MOD(-x,y) == (-x) mod y
);

//介绍了两者之间的关系
axiom(forall x:int, y:int :: {MOD(x,y), DIV(x,y)} MOD(x,y) == x - DIV(x,y) * y);

procedure test() {
  assert MOD(5,2) == 1;
  assert DIV(5,2) == 2;
  
  assert MOD(5,-2) == 1;
  assert DIV(5,-2) == -2;
  
  assert MOD(-5,2) == -1;
  assert DIV(-5,2) == -2;
  
  assert MOD(-5,-2) == -1;
  assert DIV(-5,-2) == 2;
}`
But use operator `/` and '%' will be more convenience for my program but I don't know to do this.I have also try by this way below:
`//对除法计算结果的定义
axiom(forall x:int, y:int :: { x / y }
  x >= 0 ==> x / y == x div y
);
axiom(forall x:int, y:int :: { x / y }
  x < 0 ==> -(-x / y) == (-x) div y
);

//介绍了取模的计算方式
axiom(forall x:int, y:int :: { x % y } 
   x >= 0 ==> (x % y) == x mod y
);
axiom(forall x:int, y:int :: { x % y } 
   x < 0 ==> -(-x % y) == (-x) mod y
);

//介绍了两者之间的关系
axiom(forall x:int, y:int :: { x % y, x / y } x % y == x - x / y * y);

procedure test() {
  assert 5 % 2 == 1;
  assert 5 / 2 == 2;
  
  assert 5 % -2 == 1;
  assert 5 / -2 == -2;
  
  assert -5 % 2 == -1;
  assert -5 / 2 == -2;
  
  assert -5 % -2 == -1;
  assert -5 / -2 == 2;
}`
but it dose't work.
I may need you help, teach me how to overloaded operator '/' and '%' in boogie.
truly grateful

**Comment by ZJLavender** [comment]
Or how to use other Operator to replace function MOD(x,y) and DIV(x,y) to ( x % y ) and ( x / y ) by boogie, so I can use antlr4 to decrease those operator

**Comment by emptylambda** [comment]
Hello ZJLavender, 

I guess what you wanted is user defined infix operators/function 
(most notable example being the direct support in languages like [Haskell](https://wuciawe.github.io/functional%20programming/haskell/2016/07/03/infix-functions-in-haskell.html) with backtick (`)) 

If Im not mistaken, this language feature (being able to let user defines arbitrary infix function/operator) is NOT part of standard Boogie nor is it the intended usage of Boogie.  

Now, for `%` and `/` in particular, they are special cases. 
You are not really "overloading" these operators, you are just providing what Boogie omitted by design. 
According to the language manual (this is boogie 2), these two operators come without any definition/axiomatization (see Chapter 4.0 Division and Modulo). This is because different front-end languages can have different interpretations on division and modulo (for example implicit wrap-arounds) 

Im not familiar with ANTLR, but according to its website it's a parser generator. 
In this case, generating prefix function parser shouldn't be bit problem. 
If you're interested, I'd be happy to see if I can help more :)
