### ISSUE TITLE
Bug: Assertion error

### ISSUE THREAD

**Issue by JianyiCheng** [boogie-org/boogie#116]
Hi guys,

I am using Boogie to verify my program but have experienced an issue: 

It seems the following code should pass the test but the verifier reports that the assertion might not hold... Is this a bug or I missed something?

```
var array:[int]int;

procedure F(n: int) returns (r: int)
modifies array;
{
  var a:int;
  var b:int;
  
  assume a < b;
  
  assume (forall i:int :: 0 <= i && i <= b-a ==> array[i+a] == a+i);
  assert (forall i:int :: a <= i && i <= b ==> array[i] == i);
  
}
```

Thanks,
Jianyi Cheng

**Comment by shazqadeer** [comment]
I do not see any precondition that characterizes the contents of array.  I
would not expect this program to verify.

**Comment by JianyiCheng** [comment]
Hi @shazqadeer, 

Thank you for instant reply!

I am trying to describe a group of array data indexed from ``a`` to ``b`` is **overwritten** in the procedure ``F`` using ``assume``. The original array data can be arbitrary values. This information can be used for other assertions (so we know ``array[i]`` where ``i >= a && i <= b`` have certain values). 

Maybe I wrote the program in a wrong way? I do not want to unroll the assignments to ``array[]`` in a big loop and think that using ``assume`` and ``forall`` may describe the same conditions.

Interestingly I found Boogie works with the following statements:
```
assume (forall i:int :: a <= i && i <= b ==> array[i] == i); // cond 2
assert (forall i:int :: 0 <= i && i <= b-a ==> array[i+a] == a+i); // cond 1
```

Does it means that Boogie takes cond 2 as only the sufficient condition of cond 1 but not necessary condition?

Jianyi

**Comment by shazqadeer** [comment]
I did not spot the assume before the assert.  The assertion in your program indeed holds.  Sorry for the confusion.

You are running into the problem of incomplete handling of quantifier instantiations in the automated theorem prover behind Boogie.  To prove the assertion  a <= i0 && i0 <= b ==> array[i0] == i0 for an arbitrary i0, the quantifier in the assume statement must be instantiated at i0-a but the theorem prover is not smart enough to figure it out.  This is a well-known limitation and could be addressed by providing an instantiation-triggering expression as follows:

var array:[int]int;
function f(int): bool {
    true
}

procedure F(n: int) returns (r: int)
{
  var a:int;
  var b:int;
  
  assume a < b;
  
  assume (forall i:int :: {f(i)} 0 <= i && i <= b-a ==> array[i+a] == a+i);
  assert (forall i:int :: f(i-a) && a <= i && i <= b ==> array[i] == i);
}

Now the prover attempts to prove f(i0-a) && a <= i0 && i0 <= b ==> array[i0] == i0.  The triggering hint expression {f(i)} in the assume statement looks for any expression of the form f(_) and instantiates _ for i in the quantifier.  In this case, i0-a will be chosen and that does the job.

**Comment by JianyiCheng** [comment]
Thank you so much for your solution and explanation! 
Great to know what happens behind the scene. :)

**Comment by RustanLeino** [comment]
The difference between

    assume (forall i:int :: 0 <= i && i <= b-a ==> array[i+a] == a+i);

and

    assume (forall i:int :: a <= i && i <= b ==> array[i] == i);

is significant.

For the latter, the subexpression `array[i]` will automatically be selected as a matching trigger. This is good--anytime the verifier sees an expression of the form `array[X]` for any expression `X`, it will instantiate the quantifier with `i := X`.

The former has no good matching trigger for the quantifier. The subexpression `array[i+a]` is close, but no cigar. To use it as a trigger would be asking the verifier to instantiate the quantifier anytime it sees an expression of the form `array[X+a]`, but since `+` is an interpreted function symbol, it would only be by luck that you might get an appropriate instantiation. Specifically, in your original program, the verifier is trying to prove something about `array[k]` (where I'm using `k` instead of `i` in your assertion, to avoid name clashes in my explanation). The verifier would then need to invent an `X` such that `X+a` equals `k`, and it won't do that.

In general, try to arrange so that the bound variable you want instantiated sits in a good place, like `array[i]` or `f(i)`, not `array[i+a]` or `f(i+a)`. You can read more about matching-trigger considerations here:

> K. Rustan M. Leino, Clément Pit-Claudel:
> Trigger Selection Strategies to Stabilize Program Verifiers. CAV (1) 2016: 361-381
> 

or here:

> Nada Amin, K. Rustan M. Leino, Tiark Rompf:
> Computing with an SMT Solver. TAP 2014: 20-35
> 

As described in the CAV paper, the Dafny verifier performs some rewrites of user-provided quantifications in order to get better triggers.

  Rustan

**Comment by JianyiCheng** [comment]
@RustanLeino 
Thank you so much for the comments and literatures!
It helps a lot!
