### ISSUE TITLE
Errors in generated parser.

### ISSUE THREAD

**Issue by michael-emmi** [boogie-org/boogie#132]
The parser generated using Boogie’s (Modified) Coco generates thousands of compile errors — due to inconsistencies with the names `_x` and `x` or `_T` and `t`. Here are the steps to reproduce the error, with the current head of boogie-org/boogie-partners:

```
(cd Source/Core && mono ../../../boogie-partners/CocoR/Modified/Coco.exe BoogiePL.atg -namespace Microsoft.Boogie -frames ../../../boogie-partners/CocoR/Modified)
msbuild Source/Boogie.sln
```

Here’s a sample of the errors:
```
Parser.cs(2214,217): error CS0103: The name 'T' does not exist in the current context [/Users/mje/Code/boogie-mje/Source/Core/Core-NetCore.csproj]
Parser.cs(2214,220): error CS0103: The name 'T' does not exist in the current context [/Users/mje/Code/boogie-mje/Source/Core/Core-NetCore.csproj]
Parser.cs(2214,222): error CS0103: The name 'x' does not exist in the current context [/Users/mje/Code/boogie-mje/Source/Core/Core-NetCore.csproj]
Parser.cs(2214,224): error CS0103: The name 'x' does not exist in the current context [/Users/mje/Code/boogie-mje/Source/Core/Core-NetCore.csproj]
```

**Comment by bkragl** [comment]
I also could not generate the boogie scanner/parser with the Coco/R version in the boogie-partners repository. Besides some LL1 warnings I already get the following message from Coco/R:

```
parser-- Incomplete or corrupt parser frame file
```

However, (after renaming `scanner.frame` to `Scanner.frame` and `parser.frame` to `Parser.frame`) the [latest Coco/R version](http://www.ssw.uni-linz.ac.at/coco/#CS) worked for me. After deciding on my proposal below I'll update `Source/Core/Readme.txt` accordingly.

I would propose to update Coco/R in the boogie-partners repository to the latest version. Also, since the only modification to Coco/R are the frame files, I would remove everything else from the `Modified` directory. Perhaps even better would be to move the modified frame files to the Boogie repository. However, I'm not sure if this is possible because of GNU GPL vs. Ms-PL. @RustanLeino ?
