### ISSUE TITLE
How to write invariant for 2 loop

### ISSUE THREAD

**Issue by wortin** [boogie-org/boogie#144]
I found it's hard to write invariant for some loop, even the loop with simple form like below.

```boogie
procedure f()
{
    var i : int;
    var j : int;
    var L : int;
    var src : [int][int]int;
    var des : [int]int;
    L := 4;
    i := 0;
    while(i < 10)
    invariant i <= 10 && i >= 0;
    invariant (forall k : int, l : int :: k >= 0 && k < i && l >= 0 && l < L ==> des[k * L + l] == src[k][l]);
    {
        j := 0;
        while(j < L)
        invariant j <= L && j >= 0;
        invariant (forall l : int :: l >= 0 && l < j ==> des[i * L + l] == src[i][l]);
        {
            des[i * L + j] := src[i][j];
            j := j + 1;
        }
        i := i + 1;
    }
}
```

The boogie code wants to flat the 2-D array src into 1-D array des, but the inviriants are hard to describe this intention, the error is :

```console
test.bpl(12,5): Error BP5005: This loop invariant might not be maintained by the loop.
Execution trace:
    test.bpl(8,7): anon0
    test.bpl(10,5): anon4_LoopHead
    test.bpl(14,11): anon4_LoopBody
    test.bpl(15,9): anon5_LoopHead
    test.bpl(15,9): anon5_LoopDone

Boogie program verifier finished with 0 verified, 1 error
```

Can you help me to solve this case. And by the way, the real problem is that I don't know how to write a precise invariant to prove the loop code, is there any strategy to follow or skill can be used?

**Comment by bkragl** [comment]
Your invariants are correct. You just need to put the invariant of the outer loop also as an invariant of the inner loop. Intuitively, this states that the property you have for rows (of the 2D array) `k` with `0 <= k < i` is preserved when the inner loop works on row `i`.

Note that then, for the induction step of the inner loop, the prover needs to establish that your indexing scheme (from 2D to 1D) does not have any collisions. In your variant this is easy, because the bounds of the 2D array are constants (`10` and `4`) and thus you stay in the theory of linear integer arithmetic. However, if you make these bounds symbolic, you get multiplication between variables and the prover struggles. Concretely, the axiom in the code below is actually a theorem, but is not automatically proved.

```
function idx(i:int, j:int, n:int) : int
{
  (i * n) + j
}

// This axiom is actually a theorem
axiom (forall i:int, j:int, i':int, j':int, n:int ::
  0 <= j && j < n &&
  0 <= j' && j' < n &&
  idx(i, j, n) == idx(i', j', n)
  ==>
  i == i' && j == j'
);

procedure flatten(src:[int][int]int, m:int, n:int) returns (des:[int]int)
requires m >= 0;
requires n >= 0;
ensures (forall k:int, l:int :: 0 <= k && k < m && 0 <= l && l < n ==> des[idx(k, l, n)] == src[k][l]);
{
    var i : int;
    var j : int;
    
    i := 0;
    while(i < m)
    invariant 0 <= i && i <= m;
    invariant (forall k:int, l:int :: 0 <= k && k < i && 0 <= l && l < n ==> des[idx(k, l, n)] == src[k][l]);
    {
        j := 0;
        while(j < n)
        invariant 0 <= j && j <= n;
        invariant (forall k:int, l:int :: 0 <= k && k < i && 0 <= l && l < n ==> des[idx(k, l, n)] == src[k][l]);
        invariant (forall l:int :: 0 <= l && l < j ==> des[idx(i, l, n)] == src[i][l]);
        {
            des[idx(i, j, n)] := src[i][j];
            j := j + 1;
        }
        i := i + 1;
    }
}
```
