### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by cvluca** [boogie-org/boogie#149]
Could you make the tagged release on GitHub?

I am using dafny which requires boogie to build. The official release of dafny uses the last version of boogie (i.e. git clone https://github.com/boogie-org/boogie). This makes every build be different from the last and that's hard to debug if anything wrong during the build.

I noticed that you do maintain versions under `"Source/version.cs"`, but there are no official releases on Github.

**Comment by FabianWolff** [comment]
I second this. My perspective is a little different; I work on Debian in my spare time, and I noticed that the [Debian package for boogie](https://tracker.debian.org/pkg/boogie) is quite outdated and in bad shape.

I briefly considered trying to fix this, but then I noticed that there aren't any tagged releases in the Boogie GitHub repository. This makes it difficult to know which commit should be used to update the Debian package; usually, we only package somewhat "polished" proper releases in order to avoid accidentally packaging a malfunctioning work-in-progress snapshot or something like that.

So, providing official tagged releases would help here, too (and I'm sure this also applies to other distributions beside Debian (at the very least, it does to Ubuntu et al., which are based on Debian)).

**Comment by zvonimir** [comment]
We rely on Boogie in various projects, and currently we pull it based on a hash of a particular commit to make sure our tools are released with a fixed version of Boogie. So having more official tagged releases would be helpful.

I propose that Boogie adopts the following git branching model:
https://nvie.com/posts/a-successful-git-branching-model/

In short, all development happens in the develop branch, while master branch is used only for releases. That way master branch can be "locked" so that only one-two people can push to it, which would be those that are also doing releases. We could agree on creating a release every 6 months let's say.

**Comment by shazqadeer** [comment]
https://github.com/boogie-org/boogie/releases/tag/v1.0.0

I have created the first tagged release for Boogie.

**Comment by bkragl** [comment]
@shazqadeer: I think the tagged releases should be consistent with what is in `Source/version.cs` (currently `2.4.1`; I don't know what the trailing `.10503` in the assembly version means). In particular, starting with `1.0.0` will be confusing for existing Boogie packages, for example the Debian package referenced above.

Regarding @zvonimir's suggestion: I think a separate development branch is not necessary. If (as it is already the case now) every new development is done in a separate branch/fork and goes through a pull request, then the one-two responsible people can just create a release by tagging a commit on the master branch.

**Comment by shazqadeer** [comment]
I have renamed the release v2.4.1 (deleted the old one with the incorrect version number).

@RustanLeino : FYI.

**Comment by RustanLeino** [comment]
Great. Thanks, @shazqadeer !

@bkragl , The history behind the trailing `.10503` is that .NET assembly version numbers expected a fourth number. This particular number denotes May 3 of the year 2018+1. The year used to be an offset from 2008, but was changed to 2018 when it was no longer possible to use one decimal digit for the offset.
