### ISSUE TITLE
CIVL introduction procedures can have a layer range

### ISSUE THREAD

**Issue by dricketts** [boogie-org/boogie#153]
I think introduction procedures are only supposed to have a single layer number, but the implementation currently allows a layer range:
```
var {:layer 0, 1} x: int;

procedure {:layer 0, 1} intro_x()
modifies x;
{
  x ≔ x + 1;
}

procedure {:yields} {:layer 1} update_x() 
{
  yield;
  call intro_x();
  yield;
}
```
If this is not a bug, then what does it mean for introduction procedures to have a layer range?

**Comment by shazqadeer** [comment]
My conjecture is that an introduction procedure with a side-effect cannot be called at two different layers.  Do you have a counterexample that violates my conjecture? Please attach if you do.  I will look into the code in the meantime.

**Comment by dricketts** [comment]
I think this is a counterexample:
```
var {:layer 0, 1} x: int;

procedure {:layer 0, 1} intro_x()
modifies x;
ensures x == old(x) + 1;
{
  x := x + 1;
}

procedure {:yields} {:layer 1} layer1() 
{
  yield;
  call intro_x();
  yield;
}

procedure {:yields} {:layer 0} {:refines "atomic_layer_0"} layer0()
{
  yield;
  call intro_x();
  yield;
}

procedure {:atomic} {:layer 1} atomic_layer_0()
modifies x;
{
  x := x + 1;
} 
```

**Comment by shazqadeer** [comment]
@bkragl and I had a discussion about this issue.  It is indeed a bug which will be fixed as follows:
- require introduction procedures to be annotated by a single layer rather than a layer range
- requiring that if a yielding procedure P calls an introduction procedure Q, then the disappearing layer of P matches the layer annotation of Q

The side effect of an introduction procedure will be introduced into a caller only at the layer of the introduction procedures; at other (lower) layers the call will be erased.

I will try to get this bug fixed soon.  In the meantime, please obey the restrictions mentioned above manually.  Thank you for pointing out the issue.

**Comment by shazqadeer** [comment]
My recent PR provides a fix for this issue.  However, the fix is not quite as I described above.  An introduction procedure will be allowed to have a layer range in general but if it modifies a global variable then the singleton requirement will be applied.
