### ISSUE TITLE
0 verified 0 errors when using big int 

### ISSUE THREAD

**Issue by wortin** [boogie-org/boogie#157]
I wrote a simple multiplication function by recursion:

```boogie
const UINT_MAX : int;
axiom UINT_MAX == 1000000;
procedure mul(x :int, y:int) returns (r : int)
requires x >= 0 && x <= UINT_MAX && y >= 0 && y <= UINT_MAX;
requires x * y <= UINT_MAX;
ensures r == x * y;
{
    var t : int;
    if(x == 0) {
        r := 0;
        return;
    }
    call t := mul(x - 1, y);
    r := t + y;
    return;
}
```
The requires statements limit the input params x and y to [0, UINT_MAX]  (Which means x and y are uint type) and the product of x and y is less than UINT_MAX (Which means there is no overflow).

My z3 version is 4.8.6, boogie version is 2.3.0.61016 and execute:

```
mono Boogie.exe test1.bpl 
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 0 verified, 0 errors
```

The result is 0 verified and 0 errors ?! But when I reduce the UINT_MAX to 1000, it works:

```
const UINT_MAX : int;
axiom UINT_MAX == 1000;
procedure mul(x :int, y:int) returns (r : int)
requires x >= 0 && x <= UINT_MAX && y >= 0 && y <= UINT_MAX;
requires x * y <= UINT_MAX;
ensures r == x * y;
{
    var t : int;
    if(x == 0) {
        r := 0;
        return;
    }
    call t := mul(x - 1, y);
    r := t + y;
    return;
}
```

Execute:

```
mono Boogie.exe test1.bpl 
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 1 verified, 0 errors
```

Can you help me to find what's wrong here?

**Comment by shazqadeer** [comment]
The int type in Boogie is the "unlimited" set of integers or God's integers as they are sometimes called.   So for the Boogie int type, the notion of overflow and underflow does not make sense.  You can simplify your program to the following:

procedure mul(x :int, y:int) returns (r : int)
requires x >= 0 && y >= 0;
ensures r == x * y;
{
    var t : int;
    if(x == 0) {
        r := 0;
        return;
    }
    call t := mul(x - 1, y);
    r := t + y;
    return;
}

I get 

Boogie program verifier finished with 1 verified, 0 errors

There is an orthogonal issue with Boogie that it sometimes prints 

Boogie program verifier finished with 0 verified, 0 errors

when there was a problem getting an error trace from the SMT solver. In other words, sometimes the output of "0 verified, 0 errors" cannot be trusted.

**Comment by bkragl** [comment]
@shazqadeer: I think the given program could make sense when modeling a language with bounded integers. The specification of mul encodes part of the type safety. But irrespective of that, it is a valid Boogie program.

Running Boogie with `/trace` prints
```
Verifying mul ...
  [0.279 s, 3 proof obligations]  errors
```
and looking into the prover log reveals
```
unknown
(:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))")
```

I think we should make sure that such errors are surfaced to the user and not silently swallowed. Seeing `0 verified, 0 errors` rings alarm bells, but in a larger program where some procedures got verified these errors will go unnoticed.

As a side, since we are currently discussing Z3 option cleanup in #73: the example verifies when all the Z3 options that Boogie currently sets by default are dropped.
