### ISSUE TITLE
Getting CI emails about errors from ETH Jenkins

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#158]
It seems that ETH is running CI for Boogie with Jenkins. I keep getting emails about failed builds from there. Now, Boogie CI is already being run with Travis, and so I am not sure why we would need both.

Does anyone know more about this?

**Comment by zvonimir** [comment]
@alexanderjsummers do you maybe know more about this?

**Comment by alexanderjsummers** [comment]
Hi Zvonimir! I do indeed... although I didn't know you were receiving the mails. Sorry that this isn't what you wanted - I'm sure we can fix that somehow. 

At some point in the past some (slightly ad hoc) list of people interested in the Windows build was assembled. As far as I can see, the mails go to some of us at ETH plus the following addresses: rustan.leino@outlook.com; alastair.donaldson@imperial.ac.uk; daniel.liew@imperial.ac.uk; qadeer@microsoft.com; boogie-dev@imperial.ac.uk

Is it possible that the last one expands to something you're on? Otherwise, maybe you could send me one of the mails you got and I'll take a look.

With respect to the Travis build, I don't know of the differences - I assume that's the main linux build being run. As far as I know (but that might be out of date) we are the only ones running some kind of CI for Boogie on Windows; at times there have been errors in one build or the other, so it seems to make sense to build both ways. Indeed, on the main github page for Boogie, I think the red "failed" icon is due to a link to our build server..

**Comment by alexanderjsummers** [comment]
Out of interest, do you know which Z3 version/commit the Travis build builds against?

**Comment by zvonimir** [comment]
Ok, this makes sense now, I am getting it through boogie-dev@imperial.ac.uk. Not a big deal, I'll just try to remove myself from that mailing list.

Yep, you are right about Windows builds, those are hard to set up in Travis and it is good you are running those. I guess it would then make sense to look into why WIndows builds keep failing regularly.

Currently Boogie gets built against Z3 4.8.4 in Travis. We should probably update that.

Thanks for your help!

**Comment by bkragl** [comment]
Hi @alexanderjsummers!

Is there still a desire to fix and keep this build, or is it abandoned?

The Travis build (which also generates the Boogie [NuGet package](https://www.nuget.org/packages/Boogie)) compiles Boogie with .NET Core and currently runs the lit tests with Z3 4.8.7. Details can be found in the file `.travis.yml`. It should be possible to replicate this on Windows.

If you still want to compile with `msbuild`, it is possible. However, some of the lit tests (currently 6) fail because slightly different error traces or models are produced.

It would be great to not have this ever-failing build banner :)

**Comment by alexanderjsummers** [comment]
Hi Bernhard,

Thank you for your message – I would really like the Jenkins build to work again (it did, for many years, although sensitivity to specific Z3 versions has often been a pain). It’s been on the to-do list for a while to look into the problems (I think there are several *relatively* recent sources of failures..) but it’s a bit difficult for me right now as I’m in the middle of a relocation/travelling phase between jobs. I will try to take a look over the next couple of weeks and then contact whoever seems to be involved with the relevant tests…

Thanks a lot,
Alex

**Comment by zvonimir** [comment]
Note that Travis CI now supports Windows (https://docs.travis-ci.com/user/reference/windows/) and Mac OS as well. So I think the right move (in the long run) would be to figure out how to update get the current Travis script up and running with Windows (and maybe Mac OS too).

**Comment by shazqadeer** [comment]
> 
> At some point in the past some (slightly ad hoc) list of people interested in the Windows build was assembled. As far as I can see, the mails go to some of us at ETH plus the following addresses: [rustan.leino@outlook.com](mailto:rustan.leino@outlook.com); [alastair.donaldson@imperial.ac.uk](mailto:alastair.donaldson@imperial.ac.uk); [daniel.liew@imperial.ac.uk](mailto:daniel.liew@imperial.ac.uk); [qadeer@microsoft.com](mailto:qadeer@microsoft.com); [boogie-dev@imperial.ac.uk](mailto:boogie-dev@imperial.ac.uk)
> 


Please remove qadeer@microsoft.com from that list.  This email address is not valid any more.

**Comment by bkragl** [comment]
> Note that Travis CI now supports Windows (https://docs.travis-ci.com/user/reference/windows/) and Mac OS as well. So I think the right move (in the long run) would be to figure out how to update get the current Travis script up and running with Windows (and maybe Mac OS too).

In general I agree that testing on many systems is nice. However, a few words of caution. Because there is no good way to debug this, I found it quite painful to try and setup multiple configurations in Travis (e.g., {Mono, .NET Core} x {Debug, Release}) without explicitly spelling out every combination (including the script to execute), which is not good for maintainability.  And we need a way to get a unique configuration to do the deployment.

Also, .NET Core should be stable across different platforms, so it is not the case that we have to test entirely different compilers, as was the case before.

Anyway, should we close this issue and drop the Jenkins banner from README.md for now?
