### ISSUE TITLE
Communication channels

### ISSUE THREAD

**Issue by bkragl** [boogie-org/boogie#209]
Hi! I think we have a good practice of discussing code changes, bugs, etc. in GitHub issues and pull requests. Here are a few questions to discuss further improvements.

1. It seems that the mailing list boogie-dev@imperial.ac.uk is outdated and not really used anymore. Can we drop it from the readme file?

2. Would it make sense to advise users to post certain questions somewhere else (e.g., on [Stackoverflow](https://stackoverflow.com/questions/tagged/boogie)), or do we prefer GitHub issues? Here I'm talking about questions like "How to verify X in Boogie?" as opposed to bug reports and feature requests.

3. Is there an interest in having certain discussions instant-messaging style? For example using Gitter? As an example, this is the Gitter chat room for Dafny: https://gitter.im/dafny-lang/community.
I looks useful, but I'm not sure if it would work for the Boogie community.

**Comment by zvonimir** [comment]
Good points. In my opinion, less options is better.
I would remove the mailing list. I would stick with github issues. We can leverage the labels system to mark questions as such.
My hunch is that we should not have a public instant messaging channel since then we have to commit to keeping an eye on it in almost real time. I did on occasion see a need to instant message Boogie developers, and so maybe having a boogie-org slack org would be useful. It can host channels for all boogie tools.
My 2 cents.

**Comment by bkragl** [comment]
I'm sold on your arguments for keeping all questions/reports in one place (GitHub issues) and not having the obligation to watch a public chat. I'll update README.md accordingly. 

We can keep in mind to setup Slack in case enough people show interest.
