### ISSUE TITLE
CVC4 does not support :skolemid, :qid attributes

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#224]
I would like to understand the purpose of this code block: https://github.com/boogie-org/boogie/blob/master/Source/Provers/SMTLib/SMTLibLineariser.cs#L358-L369

It introduces attributes (with quantifiers) such as `skolemid`, `qid`, and `weight`. However, it seems that CVC4 does not support these attributes (please correct me if I am wrong here), and hence benchmarks with quantifiers are crashing.

Any suggestions for how we should go about fixing this? Are these attributes used at all?

**Comment by bkragl** [comment]
In #217, @dddejan mentioned that the crashing comes from "attribute unsupported" warnings printed by CVC4. If these warnings would be printed to standard error instead of standard output (as they apparently should), the problem might be fixed, but this is not in our hands.

A workaround would be to pass the `--quiet` option to CVC4. I'm not sure if we should do this by default.

A good first step would be to understand the meaning and usage of this attributes (by Z3).

**Comment by zvonimir** [comment]
Do you understand how they are used in Boogie?
@RustanLeino Maybe you could shed some light on this? Thanks!

**Comment by bkragl** [comment]
Buried in some Z3 documentation:
**weight** (hint to the quantifier instantiation module: "more weight equals less instances")
**qid** (quantifier identifier for debugging)
**skid** (identifier prefix used to create skolem constants/functions)

Boogie looks for attributes `{:weight <int>}` and `{:qid <string>}` on quantifiers (at the same position where triggers are specified). The default for `qid` is the first 8 characters of the .bpl file + line + column, and `skid` is an increasing number.

I could not find any information on how exactly `qid` and `skid` are used by Z3, and if they can make it back to the output (e.g., in a model). It does not seem like Boogie is looking for it.

**Comment by dddejan** [comment]
It might be used by the axiom profiler (not sure what it is called). I heard there is a piece of software that can be used to debug z3 quantifier instantiations. The use case might be: run boogie, it fails due to quantifiers, produce smt log, run z3 with some options, debug. All speculation, haven't done this myself.

**Comment by zvonimir** [comment]
Ah, yes, that is a reasonable explanation! If that's the case, then I suggest we "hide" those attributes behind a `/axiomProfiler` flag or something like that, since not all solvers support them.

I am concerned about trigger patterns though. Clearly we should not remove those. Do Z3 and CVC4 support the same syntax for triggers? I was reading CVC4 documentation, but I couldn't figure this one out.

**Comment by bkragl** [comment]
> Do Z3 and CVC4 support the same syntax for triggers?

The `:pattern` attribute is predefined in the SMT-LIB standard, see http://smtlib.cs.uiowa.edu/language.shtml.

**Comment by zvonimir** [comment]
Got it! So is the SMTlib `:named` attribute the same as Z3's `:qid` attribute?

**Comment by ajreynol** [comment]
Yes, CVC4 supports the SMT-LIB standard syntax for `:pattern`.  

One thing to be careful here: CVC4 is pedantic about the trigger being a list of terms (page 33 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf), and not a standalone term.  For example:
```
(declare-fun P (Int) Bool)
(assert (forall ((x Int)) (! (P x) :pattern (P x))))
(check-sat)
```
The example is accepted by Z3 but not CVC4, since `:pattern (P x)` specifies a term and not a list of terms.  Instead this is the SMT-LIB complaint version of above:
```
(declare-fun P (Int) Bool)
(assert (forall ((x Int)) (! (P x) :pattern ((P x)))))
(check-sat)
```
where `((P x))` specifies the singleton list containing `(P x)`, which is interpreted as a "single trigger".

**Comment by bkragl** [comment]
> Got it! So is the SMTlib `:named` attribute the same as Z3's `:qid` attribute?

No. `:named` can be used to give a symbolic name to any closed subterm in the input. This name can then be used instead of the term, kind of like an inlined function. I don't think that `:qid` has an actual meaning in the formula. Also, since the attributes for quantifiers are actually given on the "body term", you cannot use `:named`, since the quantified variables are free in this term.

> One thing to be careful here: CVC4 is pedantic about the trigger being a list of terms, and not a standalone term.

Thanks for pointing this out! Boogie already specifies patterns correctly as a list of terms.

**Comment by dddejan** [comment]
> In #217, @dddejan mentioned that the crashing comes from "attribute unsupported" warnings printed by CVC4. If these warnings would be printed to standard error instead of standard output (as they apparently should), the problem might be fixed, but this is not in our hands.
> 
> A workaround would be to pass the `--quiet` option to CVC4. I'm not sure if we should do this by default.
> 
> A good first step would be to understand the meaning and usage of this attributes (by Z3).

@bkragl After looking at the code and debugging of CVC4 I actually do not think that CVC4 is doing anything wrong. Is is possible that .net is somehow not capturing the error stream correctly?

**Comment by dddejan** [comment]
Running boogie with `/proverOpt:VERBOSITY=100` gives a clearer picture 

```console
[SMT-INP-0] (get-info :name)
[SMT-ERR-0] <stdin>:28.23: warning: Attribute ':qid' not supported (ignoring this and all following uses)
[SMT-ERR-0] <stdin>:29.14: warning: Attribute ':skolemid' not supported (ignoring this and all following uses)
[SMT-ERR-0] Handling error: <stdin>:28.23: warning: Attribute ':qid' not supported (ignoring this and all following uses)
Prover error: <stdin>:28.23: warning: Attribute ':qid' not supported (ignoring this and all following uses)
[SMT-ERR-0] Handling error: <stdin>:29.14: warning: Attribute ':skolemid' not supported (ignoring this and all following uses)
Prover error: <stdin>:29.14: warning: Attribute ':skolemid' not supported (ignoring this and all following uses)
[SMT-OUT-0] (:name "cvc4")
```

So it seems like CVC4 is correctly output to stderr, but boogie is somehow misinterpreting this.
