### ISSUE TITLE
Bug: negative numbers / arithmetic leading to vacuously verified postcondition

### ISSUE THREAD

**Issue by cposkitt** [boogie-org/boogie#25]
Hello,

We've encountered a usage of Boogie that allows an obviously incorrect postcondition to be verified. A minimal example is available at:

http://rise4fun.com/Boogie/ttW

and also at the end of this post. Note that replacing "x := -N;" with "x := -1 * N;" already changes the result of the verification. We're using the latest distribution of Boogie and the latest compiled Z3 (Boogie 2.3.0.61016 and Z3 4.4.2).

Many thanks,

 -- Chris

***************************************

const N: int;
axiom 0 <= N;

procedure vacuous_post()
ensures (forall k, l: int :: 0 <= k && k <= l && l < N ==> N < N);
{
var x: int;
x := -N;
while (x != x) {
}
}

**Comment by delcypher** [comment]
@cposkitt Confirmed.

I tried this on [Symbooglix](https://github.com/symbooglix/symbooglix) and it reports two paths.

* A correct path on which ``N == 0``. The post condition holds on this path because the antecedent is always false.
* An incorrect path where where ``N > 0``. E.g. ``k == 0`` and ``l == 0`` and ``N == 1`` makes the post condition fail.

**Comment by shazqadeer** [comment]
I looked into this issue.  It appears to be a bug in the abstract interpretation code inside Boogie.  The loop invariant generation in this code is on by default.  It can be turned off by using the flag /noinfer.  If you try that flag, you will get an error trace. It appears that a false loop invariant "x == 0" is being inferred.

@RustanLeino :  Are you the best person to fix this bug?

**Comment by delcypher** [comment]
@wuestholz Thanks. That was fast work :)
