### ISSUE TITLE
Use and documentation for :msg

### ISSUE THREAD

**Issue by RustanLeino** [boogie-org/boogie#272]
Boogie allows `assert` statements and `requires` and `ensures` declarations to have an

    {:msg "My error message here}

attribute. This is not documented by the `/attrHelp` switch, but it should be.

Also, use of this feature causes the internal `ErrorInformation` object created to have a `null` source token. Specifically, in ExecutionEngine.cs, static method `CreateErrorInformation` inspects the `.ErrorMessage` field for the `requires`/`ensures` and then calls the instance method `CreateErrorInformation` with `null` as the first parameter. The Code Contract for that method says:

    Contract.Requires(1 <= tok.line && 1 <= tok.col);

This is a bit dubious, but it seems to imply that `tok` is expected to be non-null. For an `assert`, the static method `CreateErrorInformation` also sets this `tok` to `null` on at least one branch.

This null-token bug causes a crash in Dafny, which regrettably renders the `:msg` feature useless for Dafny programs. (An alternative solution would be to anticipate a `null` token in the `ErrorInformation` in Dafny, but it feels more like a Boogie issue to me.)

**Comment by shazqadeer** [comment]
I am happy to fix this in Boogie.  But what is the right fix?  I see two options:
- Use the token of the failing specification (requires/ensures/assert)
- Use Token.NoToken

The first option will not require changing the contract of CreateErrorInformation (the instance method) but the second one will require a change to:
Contract.Requires(0 <= tok.line && 0 <= tok.col);

**Comment by bkragl** [comment]
I would vote for the token of the failing spec. Although it would also possible to use the token of the failing call (in case of precondition violation) and the token of the failing return (in case of a postcondition violation).

Besides the `:msg` attribute, there is a field called `ErrorData` to programmatically set error messages on calls, preconditions, postconditions, and assertions. I'm wondering if there should be support for `:msg` on calls. Adding `ErrorData` to return commands would also be possible, but I imagine that `:msg` does not work because an internal return command does not necessarily correspond to a command in the input program on which that attribute can be attached to.
