### ISSUE TITLE
Model printing cleanup introduces infinite recursion

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#286]
The problem was introduced by this commit: https://github.com/boogie-org/boogie/commit/82ee148a3539bcb3566384c3654862f00c809a92

In particular, this call is now a recursive call that loops for ever: https://github.com/boogie-org/boogie/blob/master/Source/VCGeneration/ConditionGeneration.cs#L162

I uncovered this since Corral invokes this function. What am I maybe missing here?

**Comment by zvonimir** [comment]
@shazqadeer Any suggestions for how to resolve this? Thx!

**Comment by zvonimir** [comment]
It seems to be that this (now recursive) function should be completely removed. The one we probably want is this one: https://github.com/boogie-org/boogie/blob/master/Source/VCGeneration/ConditionGeneration.cs#L123

**Comment by shazqadeer** [comment]
Your solution appears correct.  The recursive call to the method (introduced as a result of my commit) was earlier resolving to the other method you pointed out.  If we delete the recursive, all calls to it will automatically resolve  to the other method because the last parameter to it is optional.  I will put up a PR.

**Comment by shazqadeer** [comment]
In future, if custom APIs are added to Boogie for use in Corral, there should be documentation in the Boogie code for the reason behind that API and the justification.  This would ensure "dead-code" elimination in future refactoring.
