### ISSUE TITLE
Adding a Floating-Point Type

### ISSUE THREAD

**Issue by Checkmate50** [boogie-org/boogie#29]
Boogie Team,

I'm Dietrich Geisler, and undergraduate student working for Dr. Zvonimir Rakamaric at the University of Utah.  Over the last year, I have worked on adding the floating point type to boogie based on the floating point update to z3.

The merge I am proposing adds the floating point type to boogie, allowing variables and constants to be declared as described below.  There are several issues with my implementation that I have listed.  I'm sure that there are more issues and bugs I haven't found, so if you find any issues, please let me know.

---
## Syntax Documentation

Declaring Variables:

The syntax for declaring a floating point variable is as follows:
var name: float(exp man);
Where exp is the size of the float exponent and man is the size of the float mantissa

It is also acceptable to use the following syntax:
var name: float();
This syntax assumes the float exponent to be size 8 and the mantissa to be size 24

example:
var x: float(11 53)
Declares a variable called x with a exponent sized 11 and mantissa sized 53

---

Declaring Constants:

All of the following syntax are viable for declaring a floating point constant:
float(dec)
float(exp_val man_val)
float(dec exp man)
float(exp_val man_val exp man)

Where dec is the decimal value of the constant,
exp_val/man_value are the integer values of their respective fields,
And exp/man are the sizes of their respective fields.
Note that when exp and man are not specified, they are given sizes 8 and 24 respectively

---

Defined Operations:

Given two floating point values x and y with the same size of exponent and mantissa
The following operations operate as defined in Operators section of this document:
http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml
(Note that rounding mode is always assumed to be Round to Nearest Even (RNE))
(Also note that operations not listed here are undefined)

operatation     boogie syntax
neg(x)          -x
add(x, y)       x + y
sub(x, y)       x - y
mul(x, y)       x \* y
div(x, y)       x / y
leq(x, y)       x <= y
lt(x, y)        x < y
geq(x, y)       x >= y
gt(x, y)        x > y
eq(x, y)        x == y

---

Other:

The following special values can be declared with the following syntax:
Value       Declaration
NaN         fp(nan exp man)
+oo         fp(oo exp man) OR fp(INF exp man)
-oo         fp(-oo exp man) OR fp(INF exp man)
-zero       fp(-zero exp man)
Where exp and man are the sizes of the exponent and mantissa respectively

---

Known Issues:

There is currently no way to convert from a floating point to any other data type

There is currently no way to convert the value of a variable to a floating point type
For example, the following statements fails:
var x : real;
fp(x);

Statements of the following form cause a parser error (parenthesis followed by fp constant)
... (fp(1) + fp(1));

Attempts by Boogie to infer the behavior of loops fail when floating points are involved

Describing loop behavior manually is untested (using loop unroll appears to work)

---

Details/Question: I primarily modified Absy, AbsyExpr, Parser, VCExpr, VCExprAST, TypeErasure, and SimplifyLikeLineariser.  I also added the file BigFloat.cs, allowing creation of float instances internally.  Note in particular that I modified the Parser manually; if this is incorrect or if you notice any poor or unmaintainable implementation choices, please let me know.  I would be glad to make any changes to improve performance, accuracy, or code design.

Feel free to comment below or contact me at dgeisler50@gmail.com if you have any concerns, suggestions, or questions.  Thank you for your time, and I hope this update proves valuable to the boogie community.

Best Regards,
Dietrich Geisler

**Comment by delcypher** [comment]
@Checkmate50 

Thanks for your proposal. I'm a little short on time so I can't give a complete review but here are a few things that jump out at me.

First of all I see no mention of IEEE-754 any where. That is what you are assuming ``float`` represents right?

> var name: float(exp man);
> Where exp is the size of the float exponent and man is the size of the float mantissa

I don't like the fact the type looks like a lot like a function call. I'd rather it had a template like syntax. E.g. ``float<exp,man>``. You also haven't specified if mantissa contains an implicit bit (i.e. like IEEE-754).

For common sizes we could have predefined types (e.g. ``float16``, ``float32``, ``float64`, ``float128``). Although this is syntactic sugar, these types are so common that I think would end up saving quite a lot of space.

> var name: float();
> This syntax assumes the float exponent to be size 8 and the mantissa to be size 24

I don't like the idea of an implicit size at all. Boogie is an IVL so **no syntactic sugar** unless there's a really compelling reason please.


> Declaring Constants:
>
> All of the following syntax are viable for declaring a floating point constant:
> float(dec)
> float(exp_val man_val)
> float(dec exp man)
> float(exp_val man_val exp man)
> 
> Where dec is the decimal value of the constant,
> exp_val/man_value are the integer values of their respective fields,
> And exp/man are the sizes of their respective fields.
> Note that when exp and man are not specified, they are given sizes 8 and 24 respectively

Again no implicit sizes please. I really don't want there to be multiple ways to declare floating point constants. I'm especially not keen for Boogie to have to the convert the decimal value to an approximate bit representation which may introduce rounding issues. I'd prefer something like

```
float(sign, exp_value, man_val)
```
where ``exp_value`` and ``man_va``l are expressed using the existing bitvector constant syntax. sign is a boolean which is true if the sign bit should be positive otherwise it is false

e.g.
```
float(true, 15bv5, 0bv10); // IEEE-754 binary16. Has decimal value 1.0
float(false, 15bv5, 0bv10); // IEEE-754 binary16. Has decimal value -1.0
```

Note here I'm trying to follow how SMT-LIB behaves here. The width of the ``man_val`` is 10 not 11.

An additional syntax could be

```
float<exp,man>(bitvalue)
```

where ``bitvalue`` is the bitvector representing the IEEE-754 bit pattern e.g.

```
float<5,11>(15360bv16); // IEEE-754 binary16. Has decimal value 1.0
```

> Defined Operations:

> Given two floating point values x and y with the same size of exponent and mantissa
> The following operations operate as defined in Operators section of this document:
> http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml
> (Note that rounding mode is always assumed to be Round to Nearest Even (RNE))
> (Also note that operations not listed here are undefined)

There should be a way to call the operators with a rounding mode too. I'm happy for the infix operators to assume RNE but there should be a way to use the other rounding modes if needed.

> Known Issues:
> There is currently no way to convert from a floating point to any other data type

I think SMT-LIB allows conversion between floats and bitvectors. Therefore Boogie should not have this restriction.

**Comment by Checkmate50** [comment]
Thank you for all of the advice!  You are correct about the IEEE-754 standard; thanks for pointing that out.  I will implement all of the changes you suggested; however, I had a couple of comments and questions with regards to the points you brought up:



> You also haven't specified if mantissa contains an implicit bit (i.e. like IEEE-754).

Yes, the mantissa does specify an implicit bit.  Sorry, I forgot to mention that; thanks for pointing it out.

> I'm especially not keen for Boogie to have to the convert the decimal value to an approximate bit representation which may introduce rounding issues.

I currently convert decimal to floating point by calling z3's to_fp method with the decimal as an argument; that is, I'm having z3 do the conversion as opposed to Boogie.  Since I need to add conversions from bit vectors to floating points anyway, should I also add a decimal to floating point conversion instead of having it built in to the constant declaring syntax?



> float(sign, exp_value, man_val)
> where exp_value and man_val are expressed using the existing bitvector constant syntax. sign is a boolean which is true if the sign bit should be positive otherwise it is false

I agree that having a boolean passed in for sign is correct.  With this syntax, however, how would Boogie know the size of the exponent and mantissa for the constant?  Should it be as follows?

`float<exp, man>(sign, exp_value, man_value)`

Also, I made a mistake in my write-up.  To differentiate between variable declarations and constants, I changed the keyword "float" to "fp" when declaring constants, making the examples above become:

`fp<exp, man>(sign, exp_value, man_value)`
`fp<exp, man>(bitvector)`

Sorry for the confusion.  Is this, however, a reasonable syntactic distinction to make?



> There should be a way to call the operators with a rounding mode too. I'm happy for the infix operators to assume RNE but there should be a way to use the other rounding modes if needed.

I agree.  I'm not sure how to add this option into Boogie syntax cleanly...  Do you have any suggestions?  Also, would it be ok to add this as a later version?



> I think SMT-LIB allows conversion between floats and bitvectors. Therefore Boogie should not have this restriction.

Yes, SMT-LIB allows conversions between floats and bitvectors, between floats and reals, and from signed integers to floats.  I agree that allowing these conversions is necessary; however, I again couldn't think of a way to add these operations into the Boogie syntax.  Do you have any suggestions?  The one idea I had was to add functions (i.e. real_to_float(real)), but I'm not sure of an efficient way to do this.

Thank you again!

**Comment by delcypher** [comment]
@Checkmate50 
> Thank you for all of the advice! You are correct about the IEEE-754 standard; thanks for pointing that > > out.

Don't rush into it. I think it's better that we discuss and refine the design before you jump into too much of the implementation. I'd welcome the views of @wuestholz @RustanLeino @afd here.

> I currently convert decimal to floating point by calling z3's to_fp method with the decimal as an argument; that is, I'm having z3 do the conversion as opposed to Boogie. Since I need to add conversions from bit vectors to floating points anyway, should I also add a decimal to floating point conversion instead of having it built in to the constant declaring syntax?

Are you doing that as an API call or are you using SMT-LIBv2? The maintained version of Boogie doesn't use Z3 as a library (although I think there is support, it is not maintained). My concern here is I don't really want to rely on an external tool to do this whilst parsing. I don't want to delay to translation either because there **must be only one representation of floating point constants in Boogie's Expr language**. For that reason I think it is better to initially only allow constructing floating point constants that don't require any conversion. We can push that work on to those who are generating the Boogie IVL.

What do you mean by conversion from bitvectors here? One possible is converting to and from the IEEE-754 binary representation, another is to and from the unsigned/signed integer value represented by the bitvector.

>>float(sign, exp_value, man_val)
>>where exp_value and man_val are expressed using the existing bitvector constant syntax. sign is a > >> boolean which is true if the sign bit should be positive otherwise it is false

> I agree that having a boolean passed in for sign is correct. With this syntax, however, how would >Boogie know the size of the exponent and mantissa for the constant? Should it be as follows?
>
> float<exp, man>(sign, exp_value, man_value)

I think you missed that I said the argument types of ``exp_value`` and ``man_value`` should be bitvectors which encode the size of the exponent and mantisa (note when passed you don't include the implicit bit just like SMT-LIBv2). Again see this example I already gave.

```
float(true, 15bv5, 0bv10); // IEEE-754 binary16. Has decimal value 1.0
```

I'm not sure about the first argument though. For consistency maybe it should be a ``bv1`` rather than a ``bool``.

As I mentioned there are common sizes which we probably ought to have syntactic sugar for (i.e. ``float16``, ``float32``, ``float64`` and ``float128``). We could also consider adding the C99 hex float style syntax for these common sizes.


```
var x:float16;
x := 0x1.000p+0 ; // 1.0 in decimal
x := 0x1.800p+0 ; // 1.5 in decimal
x := 0x1.800p+1 ; // 3.0 in decimal
x := 0x1.800p-1 ; // 0.75 in decimal
```

> Also, I made a mistake in my write-up. To differentiate between variable declarations and constants, > I changed the keyword "float" to "fp" when declaring constants, making the examples above become:
> fp<exp, man>(sign, exp_value, man_value)
>fp<exp, man>(bitvector)
>
> Sorry for the confusion. Is this, however, a reasonable syntactic distinction to make?

IIRC types and functions are both in their own namespace so based solely on that having ``float<exp, man>`` being the type and ``float(sign, exp, man)`` be the function for creating constants should be okay.

>> There should be a way to call the operators with a rounding mode too. I'm happy for the infix >>
>>operators to assume RNE but there should be a way to use the other rounding modes if needed.

>I agree. I'm not sure how to add this option into Boogie syntax cleanly... Do you have any suggestions? Also, would it be ok to add this as a later version?

Annotate uninterpreted functions with a ``builtin`` similar to how all bitvector functions are used currently. Boogie doesn't have enums so rather than having the rounding mode as an argument we could have another attribute.

e.g.

```
function {:builtin "fp.add" :rm "RTZ" } FP_ADD_FLOAT16(float16, float16) returns(float16);
```

---

Another minor point. You shouldn't refer to fractional bits in the floating point number as "mantissa". The terminology used by SMT-LIB and else where is "significand". I've used your terminology up to this point to avoid confusion but I think you should switch whilst you have the opportunity.

**Comment by delcypher** [comment]
@Checkmate50 
I think would be helpful to have a publicly visible working draft of your proposal. I've added a page on the Boogie wiki

https://github.com/boogie-org/boogie/wiki/Draft-floating-point-Boogie-language-extension

I think you should be able to edit it. Let me know if you can't.

**Comment by Checkmate50** [comment]
> think would be helpful to have a publicly visible working draft of your proposal. I've added a page on the Boogie wiki

Sounds good.  I'll add in my current syntax and what you've suggested so we can work from there.  Thanks for setting that up.

**Comment by Checkmate50** [comment]
I apologize for my silence the last few weeks; classes got the better of me.
I created the body of the wiki based on what @delcypher suggested above.  If the boogie team could look over the proposed syntax for the floating point type and provide feedback, I would greatly appreciate it.

I can start making some of the simpler syntax changes from my original proposal; once the syntax is agreed upon, I will of course make the necessary changes and hopefully get a working fork quickly so we can proceed from there.

Also, I had a question on proper implementation.  To allow Boogie to recognize a floating point, I directly modified the parser in the Boogie source code.  For instance, I added a "float" keyword so that the parser can create a floating point LiteralExpr or NAryExpr.  Is this correct style?  Should I be working at a higher level to avoid modifying the parser directly?

Thank you for your time.

**Comment by RustanLeino** [comment]
I'm a latecomer to this discussion, but here are my comments.

Dan remarked on the original proposal that having round parentheses in types doesn't seem very type like.  I agree.  Instead, he suggested the use of angle brackets.  I have two additional suggestions.  One is to change the order of the significand and exponent to write the significand first.  This seems more natural to me, since it is closer to scientific notation.  My other suggestion is to introduce one keyword for each floating-point type. For example, instead of the previously proposed `float<11,5>` (where I have already switched the order of the significand and exponent), you would write `float11e5`.  This is analogous to how Boogie names bit-vector types of different widths, e.g., `bv32`.

Under this proposal, the type synonyms `float16`, `float32`, `float64`, and `float128` no longer seem needed.  These types are written `float11e5`, `float24e8`, `float53e11`, and `float113e15`, respectively, which seems fine.  Users can declare their own type synonyms for these, if they prefer.

I think we should add floating-point literals to Boogie along the lines of the current bit-vector literals.  The form `float(sign, exp_value, man_val)` may make sense in the syntax-restricted LISP-like SMT-LIB format, but I don't see any reason to inherit this into Boogie.  Direct support for floating-point literals in Boogie makes for a better language solution.  I propose:

```
digit {digit} 'e' digit {digit} 'f' digit {digit} 'e' digit {digit}
```

where the part before the first `e` is the significand, the part after that `e` is the exponent, the part between `f` and the next `e` is the number of bits in the significand, and the part after the second `e` is the number of bits in the exponent.  Again, note that the natural way to write these literals is to write the significand before the exponent, hence the suggestion above to also do the same for types.  All four parts are required and all four parts are written with decimal digits.  The given significand and exponent would have to be numbers that fit within the number of bits specified by the last two parts, else a parsing error is reported.  In fact, I would go as far as to say that we shouldn't use the hidden-bit convention, but I'm open to push-back on that.  Even if we do use the hidden-bit convention, I think we should stick with using the same width specification in literals as in the types they generate (for example, the literal `1024e15f11e5` has type `float11e5`, like the syntax suggests).

I had forgotten that Boogie doesn't have hexadecimal literals.  If they were added (which would seem like a fine idea for both integers and bit-vectors, too, prefixing them with `0x`), then it is tempting to consider the following analogous form for floating-point literals:

```
'0' 'x' hexdigit {hexdigit} 'e' hexdigit {hexdigit} 'f' digit {digit} 'e' digit {digit}
```

(where the numbers specifying the number of bits would still be in decimal, just like in the types).  However, here, the first `e` and the `f` are problematical.  If we're thinking we'd like to support a hexadecimal version of floating-point literals now or in the future, then we may want to consider delimiters other than `e` and `f`.  One such possibility would be to use a caret (`^`) instead of `e` and `#` instead of `f`; for example, in this notation, the literal `0x400^F#11^5` has type `float11^5`.  (Note that `^` and `#` are currently allowed in Boogie identifiers, so this is not a big departure from what's already in Boogie.)

For negative values, it seems that a unary minus before a float-point literal may need to be treated not as a unary negation but as part of the literal.  That is, I suggest that the parser, upon getting from the scanner a unary minus followed by a floating-point literal, produces a single, negative floating-point literal.  This lets both +0 and -0 be represented.

For not-a-number, I suggest a syntax like:

```
'0' 'N' 'a' 'N' digit {digit} 'e' digit {digit}
```

possibly allowing the `N`'s also to be lower case.  Similarly, infinity would be written:

```
'0' 'o' 'o' digit {digit} 'e' digit {digit}
```

I agree with Dan that it's best to avoid floating-point literals that require conversations, for now.

**Comment by Checkmate50** [comment]
Thank you for the advice!  I would be glad to make the proposed syntax; since I'm handling floating points this way anyway, I'd imagine that I could add hexadecimal support by just directly sending the hex values to z3.  Since you are the experts, just let me know what syntax is best and I'll try to implement it quickly.

**Comment by Checkmate50** [comment]
As a point of clarification for the floating point constant declaration syntax:

digit {digit} 'e' digit {digit} 'f' digit {digit} 'e' digit {digit}

Should the digits before the f be taken literally or as bit values?  In other words, which of the following declares the value -0.5 for a float32?
1.    -1e-1f24e8    (direct numeric conversion)
2.    16777216e126f24e8    (interpreting bitwise)
3.    -0e126f24e8    (having a sign 'bit,' but otherwise interpreting bitwise)
4.    (something else I'm not thinking of)

It should be noted that while the first interpretation is the easiest for the user, there may be some confusion since I need to convert the given values to bit literals to give to z3.  That is, if I round differently than z3 does somewhere, the boogie and z3 results may differ, which could be problematic down the road.

**Comment by Checkmate50** [comment]
Hmmm, that's fair; this is by far the most intuitive format for relatively simple floating point values.  I am, however, concerned about the translation that has to occur for (A) the user to convert an already determined floating point constant to this format and (B) boogie to translate a value in this format into the SMT-LIB standard.

For an example of why the user may have to do work translating a value of this format, consider the example of representing a known float24e8 constant 0x40100000 (=2.25) in the format of (4).  The user has to shift the bit left so that the decimal can be represented as an integer, then reduce the exponent appropriately.  While the user must do some work to identify the significand and exponent of a floating point constant to convert it into the format of (2) or (3), I would argue that there are more direct translations.

As for translating this syntax into SMT-LIB, Boogie will need to remove the lead bit, then shift the exponent to match the position of the lead bit.  While this is a simple enough translation, it is more complicated (and thus prone to error) than the direct translation afforded by the other options.

**Comment by zvonimir** [comment]
I see. Let's go with (2) then. I am sure that SMT guys thought a lot about this and so maybe we should follow them.

**Comment by Checkmate50** [comment]
So I implemented the syntax proposed by @RustanLeino using my (2) interpretation of floating point constants as noted in the comment above (that is, -.5 = -0e216f24e8) and committed.  I'll modify the wiki to match these changes sometime this weekend.

**Comment by zvonimir** [comment]
This has been implemented while back.
