### ISSUE TITLE
Unexpected behaviour of :msg attribute

### ISSUE THREAD

**Issue by gauravpartha** [boogie-org/boogie#328]
It seems that since the merged pull request https://github.com/boogie-org/boogie/pull/282 (which fixes issue https://github.com/boogie-org/boogie/issues/272) the behaviour of the :msg attribute for assertions has changed in a way that I did not expect (I noticed this while trying to update a previous Boogie version to the newest one for Viper).

Before the PR, failure of the assertion `assert {:msg "test message"} false` rendered the output `test message` (using `/errorTrace:0`). Since the PR, the output is:  `.\test.bpl(2,5): Error: test message`. 

So, the output includes a part that was never specified as a value for the msg attribute (filename + Boogie position + "Error:"). This is a problem for our use case, since we directly output Boogie's output.

Was this change in behaviour intended or is it possible to adjust the behaviour to just output the value specified?

**Comment by shazqadeer** [comment]
@bkragl :  Comments?

**Comment by bkragl** [comment]
The intention in the PR was to make the behavior of `:msg` on assertions consistent with `:msg` on preconditions and postconditions. It is not possible to adjust (with a command-line flag).

I don't have an opinion about what the "right" behavior should be. We can either make it such that only the string in the attribute is printed, or you filter the output on your end.

**Comment by shazqadeer** [comment]
@RustanLeino :  Do you have a suggestion for what the behavior for :msg attribute ought to be?

**Comment by RustanLeino** [comment]
I, too, support the idea that `:msg` would work the same for all errors types (assert, precondition, etc.).

The general intention behind `:msg` is to support Boogie clients that call Boogie as an executable. For example, since Dafny calls Boogie as a .NET library, Boogie essentially returns the AST nodes for the failing Boogie `assert`'s, which means that Dafny can invent error messages at that time. In other words, Dafny takes responsibility for printing the error messages. However, I presume Viper calls Boogie as an executable (like the old Chalice had done). To save Viper from having to parse Boogie's output and then figure out how to map Boogie's error-message source locations to the locations of the Viper program, the `:msg` attribute is intended to let Viper decide on an error message that Boogie will output if the assertion/precondition/etc. fails.

This means that an assertion/precondition/etc. with a `:msg` attribute should _not_ print the Boogie source location. Such a source location is meaningless to Viper clients.

I don't know Viper's specific needs, but I can imagine a Boogie client that generates Boogie assertions and wants these to output as warnings, not errors. In that case, it would also be inappropriate for Boogie to prefix such a message with "Error:".

@gauravpartha , Is all you're asking for that, whenever Boogie has occasion to print the `:msg` message, it prints _only_ that message, nothing else? If so, then my opinion is that Boogie should support that.

**Comment by gauravpartha** [comment]
> @gauravpartha , Is all you're asking for that, whenever Boogie has occasion to print the `:msg` message, it prints _only_ that message, nothing else? If so, then my opinion is that Boogie should support that.

Yes, exactly. Your explanation of Viper's workflow is correct, thanks!
