### ISSUE TITLE
Integer Power-Of Operator?

### ISSUE THREAD

**Issue by DavePearce** [boogie-org/boogie#507]
Hey,

So I noticed there is an operator `**` for `real` data types, but not for integer types.  An example would be:

```
procedure test(x:real) returns (y:real) {
  y := x ** 2.0;
}
```

But, I want a `**` operator for integer data types.  Is there a way to do this?

**Comment by shazqadeer** [comment]
@DavePearce: I looked around for integer exponentiation and found that support it limited. It seems that SMT solvers are rather limited in what they can prove when arbitrary exponentiation is involved. This might be the reason Boogie has not attempted to provide surface syntax for it.

You might wonder why real exponentiation is provided and not integer exponentiation. I can only guess that this is because reals are closed under exponentiation so at least we can type check expressions. On the other hand, integers are not since negative exponent will typically lead to a fraction.

If you are interested only in a constant exponent, you are better off detecting that in Whiley and converting the expression into multiplication in Boogie.

**Comment by DavePearce** [comment]
Hey Shaz,

Thanks for the comments.  In the end, I used this `function` to model exponentitation:

```Boogie
function Int#pow(n : int, m : int) returns (int) {
   if (n ≠ 0) ∧ (m == 0) then 1
   else if m > 0 then n * Int#pow(n,m - 1)
   else Int#undef()
}
```

And gave it a precondition at the Whiley source level that `m != 0`.  It seems to work well enough for my use cases, though we'll see.
