### ISSUE TITLE
Deadlock in CheckerPool when maxKeepGoingSplits is used

### ISSUE THREAD

**Issue by rakamaric** [boogie-org/boogie#675]
There is a deadlock in the CheckerPool when maxKeepGoingSplits is used and the number of cores is set to 1.
You can reproduce the issue by running the following command:
```
dotnet BoogieDriver.dll /vcsMaxKeepGoingSplits:2 /trace /proverOpt:O:smt.qi.eager_threshold=100 /vcsDumpSplits test0/MaxKeepGoingSplits.bpl
```
Boogie deadlocks on waiting to acquire `checkersSemaphore`.
When you add `/vcsCores:3` the problem disappears.

**Comment by shazqadeer** [comment]
I debugged this problem a bit today and I think I know the root cause.  There is this method in SplitAndVerifyWorker:
```
async Task DoWork(int iteration, Split split, CancellationToken cancellationToken)
    {
      var checker = await split.parent.CheckerPool.FindCheckerFor(split.parent, split, cancellationToken);

      try {
        cancellationToken.ThrowIfCancellationRequested();
        await StartCheck(iteration, split, checker, cancellationToken);
        await checker.ProverTask;
        await ProcessResult(iteration, split, checker, cancellationToken);
        TotalProverElapsedTime += checker.ProverRunTime;
      }
      finally {
        await checker.GoBackToIdle();
      }
    }
```
It calls FindCheckerFor which acquires checkersSemaphore; the release happens in the call GoBackToIdle. The maximum value of checkersSemaphore is vcsCores. So if vcsCores is 1, then at most one checker is available at any time. 

There is a code path in ProcessResult where if vcsMaxKeepGoingSplits is more than 0 then tasks are created that end up calling DoWork again (presumably to verify the split VCs). The creator of these tasks waits for them. This creates a deadlock because those created tasks are blocked on the semaphore and the task that can release the semaphore is waiting on them.

**Comment by keyboardDrummer** [comment]
Thanks for the investigation both of you! That leaves for a hopefully simple fix: https://github.com/boogie-org/boogie/pull/686
