### ISSUE TITLE
Declare new finite types

### ISSUE THREAD

**Issue by thanhhai1302** [boogie-org/boogie#70]
Hi guys,

Do you know how to declare a new finite type? It seems that the keyword "finite" isn't supported in the current version. I want to declare a new type Msg with exactly four constants M1, M2, M3, M4. I tried to use the following axiom to construct a finite type and boogie didn't show any error or warning.

```
type Msg;
const unique M1: Msg;
const unique M2: Msg;
const unique M3: Msg;
const unique M4: Msg;
axiom (forall m: Msg :: m == M1 || m == M2 || m == M3 || m == M4);
```

However, when I checked two below assertions, I received the error "Error BP5001: This assertion might not hold." Do you know how to eliminate this error? These assertions seem easy to prove because of the above axiom. I don't know why boogie can't. 

```
const tMsg: Msg;
procedure Test()
{
	var tMsg1: Msg;
	havoc tMsg1;
	assert (tMsg1 == M1 || tMsg1 == M2  || tMsg1 == M3 || tMsg1 == M4);
	assert (tMsg == M1 || tMsg == M2  || tMsg == M3 || tMsg == M4);
}
```

I use Z3 v4.5.0 as a default SMT solver.

Thanks,
Thanh Hai

**Comment by delcypher** [comment]
@thanhhai1302 I'm afraid I don't know the answer to most of your questions.

At a quick glance the problem is the way Boogie is using Z3. If you pass `-proverLog:log.smt2` to Boogie and then pass that logged query to Z3 you get

```
unknown
(:reason-unknown "(incomplete quantifiers)")
(labels +3 +0 @1)
unknown
(:reason-unknown "(incomplete quantifiers)")
(labels +3 +0 @2)
unsat
```

If you drop all the options (i.e. delete the following lines)

```
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
```

and run the query again Z3 gives useful answers.

However I thought I'd just note that [Symbooglix](https://github.com/symbooglix/symbooglix) which is a symbolic execution engine for Boogie programs has no problem with your sample program and shows the program to be correct.

**Comment by RustanLeino** [comment]
The "`inite` keyword is deprecated--it is neither supported nor needed. (Unfortunately, it is mentioned very early on in the Boogie language reference manual.)
When you declare a `const`, you're only saying that the constant you declare is one of the values of its type. By declaring the constant to be "unique", you are also saying that the constant has a different value than any other "const unique".  That's all.  The type can have any number of additional values, even an infinite number of values.
In your example, you are introducing a type `Msg` and four distinct values of that type. This does not imply that those are the only four values, and thus your two assertions fail.
Note, all types in Boogie are nonempty. If you write an axiom that says a type has no values, you're are writing an axiom `false` (the verifier may or may not be clever enough to derive `false`, since the prover is not complete).
For more information about finite types and the logical encoding of quantifiers in Boogie 2, see "A Polymorphic Intermediate Verification Language: Design and Logical Encoding" by Leino and Rümmer, TACAS 2010.
  Rustan

**Comment by wilcoxjay** [comment]
@thanhhai1302 The issue is that, because your axiom is universally quantifier, Z3 doesn't know what to plug in for the quantified variable. The main way that quantifiers get instantiated is with triggers, which are patterns that tell the solver "when you see something like this, try instantiating this quantifier". Unfortunately, the way you've written the axiom, there are no good triggers, and so Z3 will never instantiate the quantifier.

Here are two ways of solving the problem at the Boogie level, and an explanation for why @delcypher's strategy of deleting options helps.

----

One (admittedly kind of strange) way to fix this problem is to introduce a function whose sole purpose is to be the trigger, like this.
```
type Msg;
const unique M1: Msg;
const unique M2: Msg;
const unique M3: Msg;
const unique M4: Msg;

function CaseSplit(m: Msg): bool { true }

axiom (forall m: Msg :: {CaseSplit(m)} m == M1 || m == M2 || m == M3 || m == M4);

const tMsg: Msg;
procedure Test()
{
    var tMsg1: Msg;
    havoc tMsg1;
    assert CaseSplit(tMsg1) && (tMsg1 == M1 || tMsg1 == M2  || tMsg1 == M3 || tMsg1 == M4);
    assert CaseSplit(tMsg) && (tMsg == M1 || tMsg == M2  || tMsg == M3 || tMsg == M4);
}
```
The function `CaseSplit` is defined to always be true, but I have annotated your axiom with the trigger `CaseSplit(m)`. Now whenever you call the function `CaseSplit`, Z3 will instantiate the axiom. Then, in your asserts, I also call `CaseSplit` on the relevant `Msg` value. This causes the assertions to pass.

----

Another way to do it, which is less general but perhaps more natural, is to introduce discriminating functions for each of the four branches, like this.

```
type Msg;
const unique M1: Msg;
const unique M2: Msg;
const unique M3: Msg;
const unique M4: Msg;

function IsM1(m: Msg): bool { m == M1 }
function IsM2(m: Msg): bool { m == M1 }
function IsM3(m: Msg): bool { m == M1 }
function IsM4(m: Msg): bool { m == M1 }

axiom (forall m: Msg :: IsM1(m) || IsM2(m) || IsM3(m) || IsM4(m));

procedure Test()
{
    var tMsg1: Msg;
    havoc tMsg1;
    assert IsM1(tMsg1) || IsM2(tMsg1) || IsM3(tMsg1) || IsM4(tMsg1);
    assert IsM1(tMsg) || IsM2(tMsg) || IsM3(tMsg) || IsM4(tMsg);
}
```
By rewriting the axiom to use these functions, Z3 will be able to *infer* a good trigger for the quantifier, so that the (also rewritten) assertions go through.

----

Finally, why does deleting the Z3 options from the prover log make the example go through? The key option is `smt.MBQI`, which stands for model-based quantifier instantiation. It is another heuristic besides triggers for Z3 to find things to plug into quantifiers. Boogie turns it off because it has a tendency to degrade solver performance or even cause loops. However, for this particular example, turning it back on makes things work better. If you want, you can turn this option on without dumping the prover log by passing `/z3opt:SMT.MBQI=true` as a command line option to Boogie. Again, be warned that this may not work well for larger examples.

**Comment by delcypher** [comment]
@RustanLeino 
> In your example, you are introducing a type Msg and four distinct values of that type. This does not imply that those are the only four values, and thus your two assertions fail.

It is true that the use of `unique` and `const` do not imply that those are the only four values. But surely combined with `axiom (forall m: Msg :: m == M1 || m == M2 || m == M3 || m == M4);` it is then the case that all instances of the type `Msg`  must be equal to one of the four constant values?

**Comment by thanhhai1302** [comment]
Thank you, everyone, for useful comments. I prefer the first strategy of @wilcoxjay since it tells the solver exactly what axiom should be used and doesn't introduce many fresh functions.
